### ISSUE TITLE
Clarify Licensing

### ISSUE THREAD

**Issue by EugeneKay** [sindremehus/subsonic#1]
Please clarify the licensing of this repository and for the Subsonic project going forward. It has been stated in the past that Subsonic is released under the GPL, but no explicit LICENSE file is provided within the repository.

If this project will not be receiving new code that is released in the Subsonic commercial product, please also provide documentation showing that the other contributors besides Sindre Mehus have released their contribution for this commercial licensing. Proceeding otherwise may be a GPL violation.

**Comment by EugeneKay** [comment]
Please also note that the [SourceForge homepage](https://sourceforge.net/projects/subsonic/) still lists the license as GPL v3, and that 6.0 [binaries are available](https://sourceforge.net/projects/subsonic/files/subsonic/6.0/) there. If those binaries are in fact GPL-licensed, please provide applicable source code for them as well. Thank you for your understanding and contributions to FOSS.

**Comment by sindremehus** [comment]
Hi Eugene,
For all practical purposes I am the sole contributor to this project so I believe changing the license is unproblematic.

I'm providing this repo with the source of the latest stable version as a service to "tinkerers" and other open-source projects.

I've added a LICENSE file now, thanks for pointing that out.

**Comment by Rovanion** [comment]
@sindremehus While I think it is regrettable that you've chosen to not release future versions of your code under the GPL I want to take this time to thank you for your work which I've enjoyed immensely over the years!

That you are "for all practical purposes" the sole contributor to subsonic is, at least from my point of view, probably because there has never been any clear path to contribute code to the project. I personally ended up sending my patch to you by email when I wanted to contribute code. But I guess this was intentional, that you never intended for it to be more than a one man project?

Either way: Since I haven't received any communication from you asking whether or not I grant you a license to include my code in your proprietary distribution of subsonic I assume that you've removed it from the code base if it was ever included?

**Comment by sindremehus** [comment]
Hi Rovanion,

Glad to hear that you have enjoyed using Subsonic :) 

And you're right: it has always been a "one-man show".  I have on several occasions been offered help from other developers and respectfully declined.

I can confirm that your patch is not included in the current code.  To be honest I don't remember if I fixed the underlying problem or if it's still a bug.

**Comment by Rovanion** [comment]
Cheers!

**Comment by EugeneKay** [comment]
Thank you for clarifying the License - I really appreciate that. It is my intent to provide a license-code-unencumbered build for my personal usage and for further packaging by others, at https://github.com/EugeneKay/subsonic. I do not have the time or interest in building against the RPM, Deb, Exe, etc targets. I don't know the current status of the "Subsonic" trademark(if any), but to prevent confusion I intend to rebrand my distribution as LibreSonic. I will more than likely provide a link-back to the commercial builds for those who desire them.

I am not concerned about the GPL-licensing for Subsonic-originated code. I do not have the time to audit the SVN history in detail, but I believe that you are correct that only code from "Sindre Mehus" remains. I am not addressing the possible issue of including GPL-built dependencies(or modifications thereof); the linking exception or this code drop should be sufficient for most concerns, but this is of course up to you to verify ;-)

Will the 6.0+ binaries remain available on SourceForge? The homepage there lists a GPLv3 license; if this does not match the binaries then they should be removed(or source provided for them).

I won't say that I'm looking forward to stewarding this abandonware, but it would be a lot more work to rewrite it. I hope that you can reconsider your decisions, though I'm sure you have good commercial reasoning behind them. Thank you again for everything!
